spring:
  application:
    name: "exercies"

app:
  datasource:
      username: "belajar_jdbc"
      password: "belajar_jdbc"
      jdbc-url: "jdbc:mysql://localhost:4000/belajar_jdbc"
      maximum-pool-size: "30"
